
}
ng {
  map duplicate() onto 'detectedDuplicate'
  map corrupt() onto 'detectedCorruption'
  map firstInSession() onto 'firstInSession'
  map timestamp() onto 'timestamp'
  map clientTimestamp() onto 'clientTimestamp'
  map remoteHost() onto 'remoteHost'
  map referer() onto 'referer'
  map location() onto 'location'
  map viewportPixelWidth() onto 'viewportPixelWidth'
  map viewportPixelHeight() onto 'viewportPixelHeight'
  map screenPixelWidth() onto 'screenPixelWidth'
  map screenPixelHeight() onto 'screenPixelHeight'
  map partyId() onto 'partyId'
  map sessionId() onto 'sessionId'
  map pageViewId() onto 'pageViewId'
  map eventType() onto 'eventType'
  map userAgentString() onto 'userAgentString'
  map userAgent().name() onto 'userAgentName'
  map userAgent().family() onto 'userAgentFamily'
  map userAgent().vendor() onto 'userAgentVendor'
  map userAgent().type() onto 'userAgentType'
  map userAgent().version() onto 'userAgentVersion'
  map userAgent().deviceCategory() onto 'userAgentDeviceCategory'
  map userAgent().osFamily() onto 'userAgentOsFamily'
  map userAgent().osVersion() onto 'userAgentOsVersion'
  map userAgent().osVendor() onto 'userAgentOsVendor'
  map eventParameters().value('price') onto 'price'
}}
